//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlBatchRunner.Win.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SqlBatchRunner.Win.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScriptPilot — SQL Runner.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arxiv.
        /// </summary>
        internal static string Archive {
            get {
                return ResourceManager.GetString("Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arxiv faylı:.
        /// </summary>
        internal static string ArchiveFile {
            get {
                return ResourceManager.GetString("ArchiveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bağlantı (Connection String).
        /// </summary>
        internal static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sınaq icrası (Dry Run).
        /// </summary>
        internal static string DryRun {
            get {
                return ResourceManager.GetString("DryRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config yüklənmə xətası: .
        /// </summary>
        internal static string Err_ConfigLoad {
            get {
                return ResourceManager.GetString("Err_ConfigLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config yazıla bilmədi: .
        /// </summary>
        internal static string Err_ConfigWrite {
            get {
                return ResourceManager.GetString("Err_ConfigWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs açıla bilmədi: .
        /// </summary>
        internal static string Err_LogsOpen {
            get {
                return ResourceManager.GetString("Err_LogsOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run xətası: .
        /// </summary>
        internal static string Err_Run {
            get {
                return ResourceManager.GetString("Err_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working folder tapılmadı. Arxiv rejimində run etdikdən sonra cəhd edin..
        /// </summary>
        internal static string Err_WorkDirNotFound {
            get {
                return ResourceManager.GetString("Err_WorkDirNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working folder açıla bilmədi: .
        /// </summary>
        internal static string Err_WorkDirOpen {
            get {
                return ResourceManager.GetString("Err_WorkDirOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qovluq.
        /// </summary>
        internal static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loglar.
        /// </summary>
        internal static string Logs {
            get {
                return ResourceManager.GetString("Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejim:.
        /// </summary>
        internal static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config: {0}.
        /// </summary>
        internal static string Msg_ConfigPath {
            get {
                return ResourceManager.GetString("Msg_ConfigPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config saxlanıldı..
        /// </summary>
        internal static string Msg_ConfigSaved {
            get {
                return ResourceManager.GetString("Msg_ConfigSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ===== RUN END ===== ExitCode={0}.
        /// </summary>
        internal static string Msg_RunEnd {
            get {
                return ResourceManager.GetString("Msg_RunEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ===== RUN START ===== (Mode={0}).
        /// </summary>
        internal static string Msg_RunStart {
            get {
                return ResourceManager.GetString("Msg_RunStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to appsettings.json aç.
        /// </summary>
        internal static string OpenAppsettings {
            get {
                return ResourceManager.GetString("OpenAppsettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log qovluğunu aç.
        /// </summary>
        internal static string OpenLogs {
            get {
                return ResourceManager.GetString("OpenLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work qovluğunu aç.
        /// </summary>
        internal static string OpenWorkDir {
            get {
                return ResourceManager.GetString("OpenWorkDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametrlər.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sıralama:.
        /// </summary>
        internal static string OrderBy {
            get {
                return ResourceManager.GetString("OrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İcra et ▶.
        /// </summary>
        internal static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yadda saxla.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL qovluğu:.
        /// </summary>
        internal static string ScriptsFolder {
            get {
                return ResourceManager.GetString("ScriptsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fayl adındakı tarix.
        /// </summary>
        internal static string Sort_FileNameDate {
            get {
                return ResourceManager.GetString("Sort_FileNameDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Əvvəl fayl adı tarixi, sonra son yazılma vaxtı.
        /// </summary>
        internal static string Sort_FileNameDateThenLastWriteTime {
            get {
                return ResourceManager.GetString("Sort_FileNameDateThenLastWriteTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son yazılma vaxtı.
        /// </summary>
        internal static string Sort_LastWriteTime {
            get {
                return ResourceManager.GetString("Sort_LastWriteTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Əvvəl son yazılma vaxtı, sonra fayl adı tarixi.
        /// </summary>
        internal static string Sort_LastWriteTimeThenFileNameDate {
            get {
                return ResourceManager.GetString("Sort_LastWriteTimeThenFileNameDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mənbə.
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xətada dayandır.
        /// </summary>
        internal static string StopOnError {
            get {
                return ResourceManager.GetString("StopOnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreationTime istifadə et.
        /// </summary>
        internal static string UseCreationTime {
            get {
                return ResourceManager.GetString("UseCreationTime", resourceCulture);
            }
        }
    }
}
